plugins:
  - remark-heading-id
  - remark-validate-links
  - remark-lint-no-multiple-toplevel-headings
  - remark-frontmatter
  - ./remark-lint-check-frontmatter.js
  - ./remark-lint-no-angle-brackets.js
  - ./remark-lint-self-close-component.js
